----UserRole


--INSERT INTO [dbo].[UserRole]
--           ([RoleName])
--     VALUES
--           ('USER')
--INSERT INTO [dbo].[UserRole]
--           ([RoleName])
--     VALUES
--           ('USER_ADMIN')
--INSERT INTO [dbo].[UserRole]
--           ([RoleName])
--     VALUES
--           ('SALES_MANAGER')
--INSERT INTO [dbo].[UserRole]
--           ([RoleName])
--     VALUES
--           ('BRANCH_MANAGER')
--INSERT INTO [dbo].[UserRole]
--           ([RoleName])
--     VALUES
--           ('GENERAL_MANAGER')
--GO