CREATE TABLE [dbo].[TmpUser]
(
	TmpUserId INT NOT NULL IDENTITY(1, 1),
	UserId INT NOT NULL,
	FirstName NVARCHAR(255) NOT NULL,
	LastName NVARCHAR(255) NOT NULL,
	Pin NVARCHAR(255) NOT NULL,
	Token NVARCHAR(2048) NOT NULL,
	ValidStartOn DATETIME2 NOT NULL,
	ValidEndOn DATETIME2 NOT NULL,
	CreatedOn DATETIME2 NOT NULL,
	UpdatedOn DATETIME2 NOT NULL,
	CONSTRAINT [PK_TmpUser] PRIMARY KEY ([TmpUserId]),
	CONSTRAINT [FK_TmpUser_UserId] FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
)
GO

GRANT SELECT, INSERT, UPDATE ON [dbo].[TmpUser] TO [SmartELockServiceLoginUserRole]
GO